[service]
type = "s3"
endpoint = "https://my-bucket.s3.us-east-1.amazonaws.com"
bucket = "my-bucket"
prefix = ""
region = "us-east-1"
access_key = "my-access-key"
secret_key = "my-secret-key"
virtual_host_style = true

[job]
workload = "upload"
# 64MiB
file_size = 67108864
run_time = "60s"
